image: docker:stable

stages:
  - build
  - deploy

cache:
  paths:
    - ./node_modules/*

build:
  stage: build
  image: docker/compose
  services:
    - docker:dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker-compose build
    - docker-compose push

before_script:
  - 'which ssh-agent || ( apk update && apk add openssh-client )'
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh

deploy_prod:
  stage: deploy
  environment:
    name: production
    url: $URL
  when: manual
  # only:
  # - master
  script:
    - ssh -o StrictHostKeyChecking=no $USER@$SERVER_IP 'bash -s' <  ./scripts/deploy.sh $ACCESS_TOKEN $CI_COMMIT_SHORT_SHA